public enum BuildingGroupType
{
    None,
    House,
    Rock,
    Tree,
    Castle,
    Bank,
    Market,
    WheatField,
    Windmill,
    Tower,
    DirectionSign,
    ArmsMarket,
    FarmerHouse,
    ArcherTrainingCenter,
    ArcherStatue,
    CavalrymanStatue
}